version: "3"
services:
  app:
    build:
      context: docker/services/php
      args:
      - TZ=Asia/Tokyo
    volumes:
    - ./:/var/www/html
    - ./docker/logs:/var/log/php
    - ./docker/services/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    environment:
    - DB_CONNECTION=mysql
    - DB_HOST=db
    - DB_DATABASE=laravel
    - DB_USERNAME=laravel
    - DB_PASSWORD=laravel
    - TZ=Asia/Tokyo
  web:
    image: nginx:1.17-alpine
    depends_on:
    - app
    ports:
    - 10010:80
    volumes:
    - ./:/var/www/html
    - ./docker/logs:/var/log/nginx
    - ./docker/services/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
    - TZ=Asia/Tokyo
